// generated by @ng-toolkit/universal
const port = process.env.PORT || 443;
const server = require('./dist/server');
var fs = require('fs'), 
 https = require('https');
var options  = { 
 key: fs.readFileSync('./a164f_23115_dced7577f5efc176046bcdc1870eb298.key'),
 cert: fs.readFileSync('./www_csstriangle_com_a164f_23115_1568678399_1696274513a5e8b8b4495af032e32d59.crt')
};
var httpsServer = https.createServer(options, server.app)
 .listen(port, () => {
  console.log("Express server listening on port " + port);
 });